# Production Profile Overrides

# Docker Compose
spring.docker.compose.enabled=true

# DataSource (use external DB in prod)
# spring.datasource.url=jdbc:postgresql://localhost:5432/alertsgpu
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# H2 Console (disabled in prod)
spring.h2.console.enabled=false
alerts.kabum.base-url=https://servicespub.prod.api.aws.grupokabum.com.br
# Scheduler
alerts.scheduler.enabled=true
alerts.scheduler.fixed-delay-ms=300000

# Logging
logging.level.com.sato.alertsgpu=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
