spring.application.name=alertsgpu
# H2 em arquivo (persistente)
spring.datasource.url=jdbc:h2:file:./data/alertsgpu;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.docker.compose.enabled=false
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

api.kabum.baseUrl = https://servicespub.prod.api.aws.grupokabum.com.br

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2